package dao;


import helper.ConnectionManager;
import model.Appointment;
import report.AppointmentContactCount;
import report.AppointmentMonthCount;
import report.AppointmentTypeCount;
import model.Contact;

import java.sql.*;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.format.TextStyle;
import java.util.*;

/** Class for querying the SQL database for appointments
 *
 */
public class AppointmentDAO {

    /** Returns a list of all appointments
     *
     * @return appointments
     */
    public List<Appointment> getAllAppointments() {
        List<Appointment> appointments = new ArrayList<>();

        String query = "SELECT a.*, c.Contact_Name " +
                "FROM appointments a " +
                "JOIN contacts c ON a.Contact_ID = c.Contact_ID";

        try {
            PreparedStatement ps = ConnectionManager.getConnection().prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                int appointmentId = rs.getInt("Appointment_ID");
                int customerId = rs.getInt("Customer_ID");
                int contactId = rs.getInt("Contact_ID");
                int userId = rs.getInt("User_ID");
                String title = rs.getString("Title");
                String description = rs.getString("Description");
                String location = rs.getString("Location");
                String type = rs.getString("Type");
                String createdBy = rs.getString("Created_By");
                String lastUpdatedBy = rs.getString("Last_Updated_By");
                LocalDateTime start = rs.getTimestamp("Start").toLocalDateTime();
                LocalDateTime end = rs.getTimestamp("End").toLocalDateTime();
                LocalDateTime createDate = rs.getTimestamp("Create_Date").toLocalDateTime();
                LocalDateTime lastUpdate = rs.getTimestamp("Last_Update").toLocalDateTime();

                appointments.add(new Appointment(appointmentId, contactId, customerId, userId, title, description, location, type, createdBy, lastUpdatedBy, start, end, createDate, lastUpdate));
            }
            ps.close();
            rs.close();
        } catch (SQLException e) {
            System.out.println("SQL Error");
            e.printStackTrace(System.out);
        }

        return appointments;
    }


    /** Method for setting appointment fields for prepared statement
     *
     * @param ps prepared statement
     * @param appointment appointment to manipulate
     * @throws SQLException
     */
    private void setAppointmentFields(PreparedStatement ps, Appointment appointment) throws SQLException {
        ps.setInt(1, appointment.getContactId());
        ps.setInt(2, appointment.getCustomerId());
        ps.setInt(3, appointment.getUserId());
        ps.setString(4, appointment.getTitle());
        ps.setString(5, appointment.getDescription());
        ps.setString(6, appointment.getLocation());
        ps.setString(7, appointment.getType());
        ps.setTimestamp(8, Timestamp.valueOf(appointment.getStartDateTime()));
        ps.setTimestamp(9, Timestamp.valueOf(appointment.getEndDateTime()));
        ps.setTimestamp(10, Timestamp.valueOf(appointment.getLastUpdate()));
        ps.setString(11, appointment.getLastUpdatedBy());
        ps.setInt(12, appointment.getUserId());
    }

    /** Method for updating a current appointment
     *
     * @param updatedAppointment appointment to update
     * @throws SQLException
     */
    public void updateAppointment(Appointment updatedAppointment) throws SQLException {
        Connection conn = ConnectionManager.getConnection();
        String query = "UPDATE appointments SET Contact_ID = ?, Customer_ID = ?, User_ID = ?, Title = ?, Description = ?, Location = ?, Type = ?, Start = ?, End = ?, Last_Update = ?, Last_Updated_By = ? "
                + "WHERE Appointment_ID = ?";

        PreparedStatement ps = conn.prepareStatement(query);

        setAppointmentFields(ps, updatedAppointment);
        ps.setInt(12, updatedAppointment.getAppointmentId());

        ps.executeUpdate();
    }

    /** Method to insert new appointment into database
     *
     * @param appointment appointment to insert
     * @return returns the autogenerated appointment ID
     * @throws SQLException
     */
    public void insertAppointment(Appointment appointment) throws SQLException {
        String query = "INSERT INTO appointments (contact_id, customer_id, user_id, title, description, location, type, start, end, last_update, last_updated_by, create_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Connection conn = ConnectionManager.getConnection();
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            ps = conn.prepareStatement(query);
            setAppointmentFields(ps, appointment); // Sets fields 1-11 common to insert and update appointment
            ps.setTimestamp(12, Timestamp.valueOf(appointment.getCreateDate()));
            ps.executeUpdate();
        }
        catch (SQLException e) {
            System.out.println("SQL Error");
            e.printStackTrace(System.out);
        }
    }


    /** Deletes the chosen appointment by ID
     *
     * @param appointmentId ID of appointment to delete
     */
    public void deleteAppointment(int appointmentId) {
        String deleteSql = "DELETE FROM appointments WHERE appointment_id = ?";

        try {
            Connection conn = ConnectionManager.getConnection();
            PreparedStatement preparedStatement = conn.prepareStatement(deleteSql);
            preparedStatement.setInt(1, appointmentId);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            System.out.println("SQL Error");
            e.printStackTrace(System.out);
        }
    }

    /** Returns appointments by client ID
     *
     * @param clientId ID of client to look up appointments for
     * @return returns a list of appointments
     */
    public List<Appointment> getAppointmentsByClient(int clientId) {
        List<Appointment> appointments = new ArrayList<>();
        String query = "SELECT * FROM appointments WHERE Customer_ID = ?";

        try {
            Connection conn = ConnectionManager.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, clientId);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                int appointmentId = rs.getInt("Appointment_ID");
                int contactId = rs.getInt("Contact_ID");
                int customerId = rs.getInt("Customer_ID");
                int userId = rs.getInt("User_ID");
                String title = rs.getString("Title");
                String description = rs.getString("Description");
                String location = rs.getString("Location");
                String type = rs.getString("Type");
                String createdBy = rs.getString("Created_By");
                String lastUpdatedBy = rs.getString("Last_Updated_By");
                LocalDateTime start = rs.getTimestamp("Start").toLocalDateTime();
                LocalDateTime end = rs.getTimestamp("End").toLocalDateTime();
                LocalDateTime createDate = rs.getTimestamp("Create_Date").toLocalDateTime();
                LocalDateTime lastUpdate = rs.getTimestamp("Last_Update").toLocalDateTime();

                appointments.add(new Appointment(appointmentId, contactId, customerId, userId, title, description, location, type, createdBy, lastUpdatedBy, start, end, createDate, lastUpdate));

            }
        }
        catch (SQLException e) {
                System.out.println("SQL Error");
                e.printStackTrace(System.out);
        }
        return appointments;
    }

    /** Returns appointment by contact
     *
     * @param contact contact to look up appointments
     * @return list of appointments
     */
    public List<Appointment> getAppointmentsByContact(Contact contact) {
        List<Appointment> appointments = new ArrayList<>();
        String query = "SELECT * FROM appointments WHERE Contact_ID = ?";

        try {
            Connection conn = ConnectionManager.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, contact.getContactId());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                int appointmentId = rs.getInt("Appointment_ID");
                int contactId = rs.getInt("Contact_ID");
                int customerId = rs.getInt("Customer_ID");
                int userId = rs.getInt("User_ID");
                String title = rs.getString("Title");
                String description = rs.getString("Description");
                String location = rs.getString("Location");
                String type = rs.getString("Type");
                String createdBy = rs.getString("Created_By");
                String lastUpdatedBy = rs.getString("Last_Updated_By");
                LocalDateTime start = rs.getTimestamp("Start").toLocalDateTime();
                LocalDateTime end = rs.getTimestamp("End").toLocalDateTime();
                LocalDateTime createDate = rs.getTimestamp("Create_Date").toLocalDateTime();
                LocalDateTime lastUpdate = rs.getTimestamp("Last_Update").toLocalDateTime();

                appointments.add(new Appointment(appointmentId, contactId, customerId, userId, title, description, location, type, createdBy, lastUpdatedBy, start, end, createDate, lastUpdate));
            }
        }
        catch (SQLException e) {
            System.out.println("SQL Error");
            e.printStackTrace(System.out);
        }

        return appointments;
    }

    /** Returns list of AppointmentTypeCount for home screen report
     *
     * @return list of AppointmentTypeCount
     */
    public static List<AppointmentTypeCount> getAppointmentCountByType() {
        List<AppointmentTypeCount> appointmentCountByType = new ArrayList<>();
        String query = "SELECT Type, COUNT(*) as count FROM appointments GROUP BY Type";
        try {
            Connection conn = ConnectionManager.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String type = rs.getString("Type");
                int count = rs.getInt("count");
                appointmentCountByType.add(new AppointmentTypeCount(type, count));
            }
        }

        catch (SQLException e) {
            System.out.println("SQL Error");
            e.printStackTrace(System.out);
        }
        return appointmentCountByType;
    }

    /** Returns list of AppointmentMonthCount for home screen report
     *
     * @return list of AppointmentMonthCount
     */
    public static List<AppointmentMonthCount> getAppointmentCountByMonth() {
        List<AppointmentMonthCount> appointmentCountByMonth = new ArrayList<>();
        String query = "SELECT EXTRACT(MONTH FROM Start) as month, COUNT(*) as count FROM appointments GROUP BY month";
        try {
            Connection conn = ConnectionManager.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int monthNumber = rs.getInt("month");
                String monthName = Month.of(monthNumber).getDisplayName(TextStyle.FULL, Locale.getDefault());
                int count = rs.getInt("count");
                appointmentCountByMonth.add(new AppointmentMonthCount(monthName, count));
            }
        }

        catch (SQLException e) {
            System.out.println("SQL Error");
            e.printStackTrace(System.out);
        }
        return appointmentCountByMonth;
    }

    /** Returns list of AppointmentContactCount for home screen report
     *
     * @return list of AppointmentContactCount
     */
    public static List<AppointmentContactCount> getAppointmentCountByContact() {
        List<AppointmentContactCount> appointmentCountByContact = new ArrayList<>();
        String query = "SELECT c.Contact_Name, COUNT(*) as count FROM appointments a JOIN contacts c ON a.Contact_ID = c.Contact_ID GROUP BY c.Contact_Name";
        try {
            Connection conn = ConnectionManager.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String contactName = rs.getString("Contact_Name");
                int count = rs.getInt("count");
                appointmentCountByContact.add(new AppointmentContactCount(contactName, count));
            }
        }

        catch (SQLException e) {
            System.out.println("SQL Error");
            e.printStackTrace(System.out);
        }
        return appointmentCountByContact;
    }
}